import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// Local font for Bangers-Regular
const geistMono = localFont({
  src: "./fonts/Bangers-Regular.ttf",
  variable: "--font-geist-mono",
  weight: "400",
});

export const metadata = {
  title: "Remember?",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen"> {/* Make body a flex container with full height */}
        {/* Force apply geistMono only to Navbar and Footer */}
        <div className={`${geistMono.variable} font-bangers antialiased`}>
          <Navbar />
        </div>

        {/* Content area with fixed height and scrollable if overflow */}
        <main className="flex-grow overflow-y-auto">
          {children}
        </main>

        <div className={`${geistMono.variable} font-bangers antialiased pb-8`}>
          <Footer />
        </div>
      </body>
    </html>
  );
}
